create_window_err_msg   db "SDL_CreateWindow Error: %s", 10, 0
create_renderer_err_msg db "SDL_CreateRenderer Error: %s", 10, 0
render_fill_error_msg db "SDL_RenderFillRect Error: %s", 10, 0
update_window_surface_error_msg db "SDL_UpdateWindowSurface Error: %s", 10, 0
set_render_draw_color_error_msg db "SDL_SetRenderDrawColor Error: %s", 10, 0 
log_here_msg db "Logged here", 10, 0 
left_arrow_pressed_msg db "left_arrow_pressed_msg", 10, 0 
right_arrow_pressed_msg db "right_arrow_pressed_msg", 10, 0 
up_arrow_pressed_msg db "up_arrow_pressed_msg", 10, 0 
down_arrow_pressed_msg db "down_arrow_pressed_msg", 10, 0 